EasyAce/urls.py
#EasyAceSite/urls
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static

from . import views

urlpatterns = patterns('',
    url(r'^$', 'EasyAce.views.getHome', name='home'),
    url(r'^testimonial/$', 'EasyAce.views.getTestimonial', name='testimonial'),
    url(r'^welfare/$', 'EasyAce.views.getWelfare', name='welfare'),
    url(r'^aboutus/$', 'EasyAce.views.getAbout', name='about'),
    url(r'^contact/$', 'EasyAce.views.getContact', name='contact'),
    url(r'^faq/$', 'EasyAce.views.getFAQ', name='faq'),
    url(r'^zh/$', 'EasyAce.views.getHomeZH', name='homeZH'),
    url(r'^zh/testimonial/$', 'EasyAce.views.getTestimonialZH', name='testimonialZH'),
    url(r'^zh/welfare/$', 'EasyAce.views.getWelfareZH', name='welfareZH'),
    url(r'^zh/aboutus/$', 'EasyAce.views.getAboutZH', name='aboutZH'),
    url(r'^zh/contact/$', 'EasyAce.views.getContactZH', name='contactZH'),
    url(r'^zh/faq/$', 'EasyAce.views.getFAQZH', name='faqZH'),
	url(r'^admin/$', include(admin.site.urls)),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
	urlpatterns += patterns('',
		url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
			{'document_root': settings.MEDIA_ROOT}),
	)

Tutor/urls.py
#Tutor/urls
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.getTutor, name='tutor'),
    url(r'^(?P<subject_title>[a-z|A-Z]+)/$', views.getTutorBySubject, name='tutor_subject'),
]

Tutor/models.py
from django.db import models
from django.conf import settings
# Create your models here.
class Subject(models.Model):
    LEVEL = (
        ('P', 'Primary School'),
        ('O', 'O-level'),
        ('A', 'A-level'),
        ('D', 'Not Specified'),
    )
    level = models.CharField(max_length=2, choices=LEVEL, default='D')
    title = models.CharField(max_length=100)
    def __str__(self):
        return self.title

class Education(models.Model):
    LEVEL = (
        ('J', 'Junior college'),
        ('P', 'Polytechnic'),
        ('U', 'University'),
        ('D', 'Not Specified'),
    )
    level = models.CharField(max_length=2, choices=LEVEL, default='D')
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Tutor(models.Model):
    REGION = (
        ('E', 'East'),
        ('W', 'West'),
        ('C', 'Central'),
        ('N', 'North'),
        ('D', 'Unknown'),
    )
    TIME = (
        ('M', 'Morning'),
        ('A', 'Afternoon'),
        ('E', 'Evening'),
        ('D', 'Not Specified'),
    )
    GENDER = (
        ('F', 'Female'),
        ('M', 'Male'),
        ('D', 'Not Specified'),
    )
    TYPE = (
        ('F', 'Full-Time'),
        ('P', 'Part-Time'),
    )
    region = models.CharField(max_length=2, choices=REGION, default='D')
    gender = models.CharField(max_length=2, choices=GENDER, default='D')
    name = models.CharField(max_length=100)
    photo = models.ImageField(upload_to="tutor")
    subject_teach = models.ManyToManyField(Subject)
    education = models.ManyToManyField(Education,through='Graduation')
    type = models.CharField(max_length=2, choices=TYPE, default='P')
              
    def __str__(self):
        return self.name


class Graduation(models.Model):
    tutor = models.ForeignKey(Tutor)
    education = models.ForeignKey(Education)
    #date = models.DateTimeField('Date of graduation', blank = True)
    description = models.CharField(max_length=500, blank = True)

EasyAce/views.py
#EasyAceSite/views
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import  RequestContext, loader

def getHome(request):
    template = loader.get_template('index.html')
    context = RequestContext(request,{})
    return HttpResponse(template.render(context))

def getTestimonial(request):
    template = loader.get_template('testimonial.html')
    context = RequestContext(request,{})
    return HttpResponse(template.render(context))

def getWelfare(request):
    template = loader.get_template('welfare.html')
    context = RequestContext(request,{})
    return HttpResponse(template.render(context))

def getAbout(request):
    template = loader.get_template('about.html')
    context = RequestContext(request,{})
    return HttpResponse(template.render(context))

def getContact(request):
    template = loader.get_template('contact.html')
    context = RequestContext(request,{})
    return HttpResponse(template.render(context))

def getFAQ(request):
    template = loader.get_template('faq.html')
    context = RequestContext(request,{})
    return HttpResponse(template.render(context))

#the following is for Chinese version of site
def getHomeZH(request):
    template = loader.get_template('index_zh.html')
    context = RequestContext(request,{})
    return HttpResponse(template.render(context))

def getTestimonialZH(request):
    template = loader.get_template('testimonial_zh.html')
    context = RequestContext(request,{})
    return HttpResponse(template.render(context))

def getWelfareZH(request):
    template = loader.get_template('welfare_zh.html')
    context = RequestContext(request,{})
    return HttpResponse(template.render(context))

def getAboutZH(request):
    template = loader.get_template('about_zh.html')
    context = RequestContext(request,{})
    return HttpResponse(template.render(context))

def getContactZH(request):
    template = loader.get_template('contact_zh.html')
    context = RequestContext(request,{})
    return HttpResponse(template.render(context))

def getFAQZH(request):
    template = loader.get_template('faq_zh.html')
    context = RequestContext(request,{})
    return HttpResponse(template.render(context))

Tutor/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import  RequestContext, loader
from .models import Tutor, Subject

def getTutor(request):
    template = loader.get_template('Tutors.html')
    tutor = Tutor.objects.all()
    context = RequestContext(request, {
            'tutors':tutor,
    })
    return HttpResponse(template.render(context))

def getTutorBySubject(request, subject_title):
    template = loader.get_template('Tutors.html')
    try:
        subject = Subject.objects.get(title=subject_title)
        tutor = Tutor.objects.filter(subject_teach=subject)
    except Subject.DoesNotExist:
        raise Http404("Subject does not exist")
    context = RequestContext(request, {
            'tutors':tutor,
    })
    #name = ', '.join([p.name for p in tutor])
    return HttpResponse(template.render(context))

Tutor/templates/Tutors.html
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

	<!-- Basic Page Needs
  ================================================== -->
	<meta charset="utf-8">
	<title>Our Tutors | Easy Ace</title>
	<meta name="description" content="">
	<meta name="author" content="">

	<!-- Mobile Specific Metas
  ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- CSS
  ================================================== -->
    {% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'stylesheets/base.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'stylesheets/skeleton.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'stylesheets/layout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheets/flexslider.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheets/prettyPhoto.css' %}">
    
    <!-- CSS
  ================================================== -->
 	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
    <script src="{% static 'js/jquery.flexslider-min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script>
    function myFunction() {

        var len = document.form.check.length;
        var str = "";
        for (var i=0; i < len; i++)
        {
            str .=document.form.check[0].value+",";
        }
        document.form.action = str;
        document.form.submit();
        //window.location.replace(str);
    }
    </script>

	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<!-- Favicons    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! THIS PART need to MODIFIED, CREATE NEW ICON!!!!!!!!!!!!
	================================================== -->
	<link rel="shortcut icon" href="{% static 'images/icon.ico' %}">
    <link rel="apple-touch-icon" href="{% static 'images/c.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'images/b.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'images/a.png' %}">

</head>
<body>



	<!-- Primary Page Layout
	================================================== -->
	<header id="header" class="site-header" role="banner">
    <div id="header-inner" class="container sixteen columns over">
    <hgroup class="one-third column alpha">
    <h1 id="site-title" class="site-title">
    <a href="index.html" id="logo"><img src="{%static 'images/Logo_Easy Ace.jpeg'%}" alt="EasyAce logo" height="140" width="280" /></a>
    </h1>
    </hgroup>
    <div align="right">
    <a href="http://www.easyace.sg/zh">简体中文</a>
    </div>
    <nav id="main-nav" class="two thirds column omega">
    <ul id="main-nav-menu" class="nav-menu">
        <li id="menu-item-1">
            <a href="http://www.easyace.sg">Home</a>
        </li>
        <li id="menu-item-2">
            <a href="http://www.easyace.sg/aboutus">About us</a>
        </li>
        <li id="menu-item-3" class="current">
            <a href="http://www.easyace.sg/tutor">Our Tutors</a>
        </li>
        <li id="menu-item-4">
            <a href="http://www.easyace.sg/welfare">Welfare</a>
        </li>
        <li id="menu-item-5">
            <a href="http://www.easyace.sg/testimonial">Why us</a>
        </li>
        <li id="menu-item-6">
            <a href="http://www.easyace.sg/contact">Contact us</a>
        </li>
    </ul>
    </nav>
    </div>
    </header>
    <div class="container">
        <div class = "sixten columns">
    <div><form>
    <div class= "three columns">Subject:</div>
    <div class= "three columns"><input type="checkbox" name="subject" value="ma">Math</div>
    <div class= "three columns"><input type="checkbox" name="subject" value="ch">Chinese</div>
    <div class= "three columns"><input type="checkbox" name="subject" value="en">General Paper</div>
    <div class= "three columns"><input type="checkbox" name="subject" value="ph">Physics</div>
    </form></div>

    <div><form>
        <div class= "three columns">    Gender:</div>

        <div class= "three columns"><input type="checkbox" name="gender" value = "m">Male</div>
        <div class= "nine columns"><input type="checkbox" name="gender" value = "f">Female</div>
    </form> </div>

    <div><form>
        <div class= "three columns">    Region:</div>

    <div class= "three columns"><input type="checkbox" name="region" value = "c">Central</div>
    <div class= "three columns"><input type="checkbox" name="region" value = "e">East</div>
    <div class= "three columns"><input type="checkbox" name="region" value = "n">North</div>
    <div class= "three columns"><input type="checkbox" name="region" value = "w">West</div>
    </form> </div>

    <div><form>
        <div class= "three columns">    Education Background:</div>

    <div class= "three columns"><input type="checkbox" name="education" value="j">Junior College</div>
    <div class= "three columns"><input type="checkbox" name="education" value="p">Polytechnic</div>
    <div class= "six columns"><input type="checkbox" name="education" value="u">University</div>
    </form></div>
    </div>
    <br>    <br>    <br>    <br>    <br>    <br>
    &nbsp&nbsp&nbsp&nbsp&nbsp<a class="myButtonSmall" id = "myBtn">Search</a>
    <script>
        document.getElementById("myBtn").addEventListener("click", myFunction)
    </script>
    <br><br>
    {% if tutors %}
        <ul>
            {% for Tutor in tutors %}
            <li>
                                <hr>
               <div class="container">
                <article class="four columns main-content">
                    <img src="../media/{{ Tutor.photo.url }}" height = "200">
                    <br>&nbsp
                </article>
                <article class="six columns main-content">
                    <p><strong>Name:</strong> {{ Tutor.name}}</p>
                    <p><strong>Gender:</strong> {{ Tutor.get_gender_display}}</p>
                    <p><strong>{{Tutor.get_type_display}}&nbspTutor</strong></p>
                    <p><strong>Region:</strong> {{ Tutor.get_region_display}}</p>
                </article>
                <article class="six columns main-content">
                    <p><strong>Education: </strong><br>
                            {%for edu in Tutor.education.all%}
                            &nbsp&nbsp&nbsp{{edu.get_level_display}}<br>
                            {%endfor%}
                    </p>
                    <p><strong>Subject: </strong><br>
                            {%for sb in Tutor.subject_teach.all %}
                            &nbsp&nbsp&nbsp{{sb.get_level_display}}&nbsp{{sb.title}}<br>
                            {%endfor%}
                    </p>
                </article>
                </div>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No tutors are available</p>
    {% endif %}
    </div>
<footer>

<div class="footer-inner container">
<div class="social footer-columns one-second column">
<h2><i class="icon-bullhorn icon-large"></i> Get Social</h2>

<a href="https://www.linkedin.com/company/easy-ace-pte-ltd?trk=top_nav_home" class = "three columns main-content"><i class="icon-linkedin-sign icon-large"></i> LinkedIn</a>

</div>
</div>

<div id="footer-base">
<div class="container">
<div class="eight columns">
Copyright &copy; 2015 Easy Ace Pte. Ltd.
</div>
</div>
</div>

</footer>

<!-- End Document
================================================== -->

<script src="js/jquery.prettyPhoto.js"></script>
</body>
</html>

Tutor/templates/about.html
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

	<!-- Basic Page Needs
  ================================================== -->
	<meta charset="utf-8">
	<title>About us | Easy Ace</title>
	<meta name="description" content="">
	<meta name="author" content="">

	<!-- Mobile Specific Metas
  ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- CSS
  ================================================== -->
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheets/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheets/skeleton.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheets/layout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheets/flexslider.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheets/prettyPhoto.css' %}">
    
    <!-- CSS
  ================================================== -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
    <script src="{% static 'js/jquery.flexslider-min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Favicons    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! THIS PART need to MODIFIED, CREATE NEW ICON!!!!!!!!!!!!
    ================================================== -->
    <link rel="shortcut icon" href="{% static 'images/icon.ico' %}">
    <link rel="apple-touch-icon" href="{% static 'images/c.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'images/b.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'images/a.png' %}">

</head>
<body>



    <!-- Primary Page Layout
    ================================================== -->

    <header id="header" class="site-header" role="banner">
    <div id="header-inner" class="container sixteen columns over">
    <hgroup class="one-third column alpha">
    <h1 id="site-title" class="site-title">
    <a href="http://www.easyace.sg" id="logo"><img src="{%static 'images/Logo_Easy Ace.jpeg'%}" alt="EasyAce logo" height="140" width="280" /></a>
    </h1>
    </hgroup>
    <div align ="right">
    <a href="http://www.easyace.sg/zh">简体中文</a>
    </div>
    <nav id="main-nav" class="two thirds column omega">
    <ul id="main-nav-menu" class="nav-menu">
            <li id="menu-item-1">
    <a href="http://www.easyace.sg">Home</a>
    </li>
    <li id="menu-item-2"  class="current">
    <a href="http://www.easyace.sg/aboutus">About us</a>
    </li>
    <li id="menu-item-3">
    <a href="http://www.easyace.sg/welfare">Welfare</a>
    </li>
    <li id="menu-item-4">
    <a href="http://www.easyace.sg/testimonial">For Student</a>
    </li>
    <li id="menu-item-5">
    <a href="http://www.easyace.sg/faq">For Tutor</a> 
    </li>
    <li id="menu-item-6">
    <a href="http://www.easyace.sg/contact">Contact us</a>
    </li>
    </ul>
    </nav>
    </div>
    </header>

	<div class="container">
        <div class="tagline">
        <p>Easy Ace is a Tuition Service Provider founded by a group of students from NUS and

NTU, who wish to provide high quality tuition to the students in Singapore. We treat 

tuition as a service instead of just a business.

As we have been through Singapore’s education system ourselves, we know the 

pressure and difficulty it imposes on each student. Therefore, we aim to develop the 

most people-oriented service to make every tutor enjoy teaching and every student 

enjoy studying.</p>
<hr>
<ul>
    <li><strong>Our Mission</strong></li>
    <li>To fulfil the need of the community through our service</li>
    <li><br><strong>Our Vision</strong></li>
    <li>To become an extraordinary world-leading service provider</li>
    <li><br><strong>Our Core Values</strong></li>
    <li>Passion, Integrity, Accountability, Professionalism</li>
</ul>
        </div>
        <hr>

        <article class = "one column left-sidebar">
            &nbsp
        </article>
		<article class="five columns main-content" align="center">
            <a><img src="{%static 'images/IMG_1619.JPG'%}" height="299" width="200" /></a>
            <br>Christoph Wang Xiaoran
            <br>Executive Director, CFO
            <br><br>Discover the unkown universe;
            <p>Uncover the human nature.</p>
        </article>
        <!-- End Left Sidebar -->
        
        
        <article class="five columns main-content" align="center">
            <a><img src="{%static 'images/IMG_1620.JPG'%}" height="299" width="200" /></a>
            <br>Kent Lin Yeyang  
            <br>CEO, President
            <br><br>Opportunity favours only the 
            <p>prepared minds.</p>
        </article>
        <!-- End main Content -->
        
        <article class="five columns main-content" align="center">
            <a><img src="{%static 'images/IMG_1621.JPG'%}" height="299" width="200" /></a>
            <br>Qiu Minhui  
            <br>Secretary
            <br><br>When the going gets tough,
            <p>tough gets going.</p>
        </article>
        <!-- End Right Sidebar -->
    <hr>




        <article class="four columns left-sidebar">
            <a><img src="{%static 'images/IMG_1622.JPG'%}" height="299" width="200" /></a>
            <br>Bustin Jin Bo
            <br>Manager, Student Department
            <br><br>Strive not to be a success,
            <p>but rather to be of value.</p>
        </article>
        <!-- End Left Sidebar -->
        
        <article class="four columns main-content">
            <a><img src="{%static 'images/IMG_1623.JPG'%}" height="299" width="200" /></a>
            <br>Lenna Yang Yinlun 
            <br>Manager, Tutor Department
            <br><br>An apple a day keeps the doctor
            <p>away.</p>
        </article>
        <!-- End main Content -->

         <article class="four columns main-content">
            <a><img src="{%static 'images/IMG_1624.JPG'%}" height="299" width="200" /></a>
            <br>Elaine Sun Yuanyuan  
            <br>Marketing Director
            <br><br>Dance like there's nobody watching, love like you'll never be hurt, sing like there's nobody listening, and live like it's heaven on earth 
        </article>
        
        <ariticle class="four columns right-sidebar">
            <a><img src="{%static 'images/IMG_1625.JPG'%}" height="299" width="200" /></a>
            <br>Stephen Chen Shijian  
            <br>Vice Marketing Director
            <br><br>Keep your eyes on the stars,
            <p>and your feet on the ground.</p>
        </ariticle>

    </div>
<br><br>

<footer>

<div class="footer-inner container">
<div class="social footer-columns one-second column">
<h2><i class="icon-bullhorn icon-large"></i> Get Social</h2>

<a href="https://www.linkedin.com/company/easy-ace-pte-ltd?trk=top_nav_home" class = "three columns main-content"><i class="icon-linkedin-sign icon-large"></i> LinkedIn</a>

</div>
</div>

<div id="footer-base">
<div class="container">
<div class="eight columns">
Copyright &copy; 2015 Easy Ace Pte. Ltd.
</div>
</div>
</div>

</footer>

<!-- End Document
================================================== -->

<script src="js/jquery.prettyPhoto.js"></script>
</body>
</html>

Tutor/templates/contact_zh.html
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

	<!-- Basic Page Needs
  ================================================== -->
	<meta charset="utf-8">
	<title>联系我们 | 易英教育</title>
	<meta name="description" content="">
	<meta name="author" content="">

	<!-- Mobile Specific Metas
  ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- CSS
  ================================================== -->
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheets/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheets/skeleton.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheets/layout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheets/flexslider.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheets/prettyPhoto.css' %}">
    
    <!-- CSS
  ================================================== -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
    <script src="{% static 'js/jquery.flexslider-min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="http://maps.googleapis.com/maps/api/js"></script>
    <script>
    function initialize() {
        var myLatLng = {lat:1.33002, lng:103.95123};
        var mapProp = {
            center:myLatLng,
            zoom:15,
            mapTypeId:google.maps.MapTypeId.ROADMAP
        };
        var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
        var marker=new google.maps.Marker({
            position:myLatLng,
        });

        marker.setMap(map);
    }
    google.maps.event.addDomListener(window, 'load', initialize);
    </script>

    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Favicons    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! THIS PART need to MODIFIED, CREATE NEW ICON!!!!!!!!!!!!
    ================================================== -->
       <link rel="shortcut icon" href="{% static 'images/icon.ico' %}">
    <link rel="apple-touch-icon" href="{% static 'images/c.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'images/b.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'images/a.png' %}">

</head>
<body>



    <!-- Primary Page Layout
    ================================================== -->

    <header id="header" class="site-header" role="banner">
    <div id="header-inner" class="container sixteen columns over">
    <hgroup class="one-third column alpha">
    <h1 id="site-title" class="site-title">
    <a href="http://www.easyace.sg" id="logo"><img src="{%static 'images/Logo_Easy Ace.jpeg'%}" alt="EasyAce logo" height="140" width="280" /></a>
    </h1>
    </hgroup>
    <div align="right">
    <a href="http://www.easyace.sg">English</a>
    </div>
    <nav id="main-nav" class="two thirds column omega">
    <ul id="main-nav-menu" class="nav-menu">
        <li id="menu-item-1">
    <a href="http://www.easyace.sg/zh">首页</a>
    </li>
    <li id="menu-item-2">
    <a href="http://www.easyace.sg/zh/aboutus">关于我们</a>
    </li>
    <li id="menu-item-3">
    <a href="http://www.easyace.sg/zh/welfare">我们的福利</a>
    </li>
    <li id="menu-item-4">
    <a href="http://www.easyace.sg/zh/testimonial">学生事宜</a>
    </li>
    <li id="menu-item-5">
    <a href="http://www.easyace.sg/zh/faq">教师事宜</a> 
    </li>
    <li id="menu-item-6"   class="current">
    <a href="http://www.easyace.sg/zh/contact">联系我们</a>
    </li>
    </ul>
    </nav>
    </div>
    </header>

	<div class="container">
        <div class="eight columns main-content">
        <address>
            <h2>联系我们</h2>
            <p>手机： +65 9821 9678</p>
            <p>电子邮箱： <a href="mailto:tuition@easyace.sg">tuition@easyace.sg</a></p>
            <p>地址：</p>
            <p>Upper Changi Road East Summer Gardens</p>
            <p>Singapore 486163</p> 
        </address> 
        </div>
        <div class= "eight columns main-content"> 
            <div id="googleMap" style="width:500px;height:380px;"></div>
        </div>   
    </div>
    <br><br>
<br><br><br><br><br><br><br><br><br><br>
<footer>

<div class="footer-inner container">
<div class="social footer-columns one-second column">
<h2><i class="icon-bullhorn icon-large"></i> 社区</h2>

<a href="https://www.linkedin.com/company/easy-ace-pte-ltd?trk=top_nav_home" class = "three columns main-content"><i class="icon-linkedin-sign icon-large"></i> 领英</a>

</div>
</div>

<div id="footer-base">
<div class="container">
<div class="eight columns">
Copyright &copy; 2015 Easy Ace Pte. Ltd.
</div>
</div>
</div>

</footer>

<!-- End Document
================================================== -->

<script src="js/jquery.prettyPhoto.js"></script>
</body>
</html>